### ISSUE TITLE
Proposta de leiaute

### ISSUE THREAD

**Issue by nicholaseduardo** [nv-nads-ifms/seleta-institucional#7]
Descrever uma proposta de leiaute (estrutura e organização) para o site da SELETA com base no [documento inicial de estrutura do site](https://github.com/nv-nads-ifms/seleta-institucional/blob/master/docs/Projeto%20Site%20Seleta.pdf).

Utilize a ferramenta [pencil ](https://pencil.evolus.vn/)para montar o protótipo visual ou outra que achar mais simples.

Publique sua proposta no **formato imagem**.

**Comment by jheniffer-cioca** [comment]
![untitled_page](https://user-images.githubusercontent.com/56830863/68482810-b6edee00-0210-11ea-8d86-00419438473a.png)


A proposta de leiaute acima foi feito por todos os integrantes da manhã.

**Comment by xxcarloslk** [comment]
![untitled_page](https://user-images.githubusercontent.com/47575725/69429352-bb82ce00-0d09-11ea-892d-7df0b7d65aae.png)

**Comment by Mayaraaaa** [comment]
[Uploading Captura de tela de 2019-11-22 09-43-30.xcf…]()

**Comment by Mayaraaaa** [comment]
tela eventos

**Comment by gabriela-barros** [comment]
![untitled_page](https://user-images.githubusercontent.com/56830678/69431310-d8b99b80-0d0d-11ea-81b6-121576736070.png)

Tela "SOBRE NÓS"

**Comment by Mayaraaaa** [comment]
![Captura de tela de 2019-11-22 09-43-30](https://user-images.githubusercontent.com/51915941/69431157-8e381f00-0d0d-11ea-9acc-704a35c4c6e3.png) tela evemtos

**Comment by Mayaraaaa** [comment]
![untitled_page](https://user-images.githubusercontent.com/51915941/69431545-5aa9c480-0d0e-11ea-8e78-1a72b567a488.png)
TELA EVENTOS

**Comment by gabriela-barros** [comment]
![noticia](https://user-images.githubusercontent.com/56830678/69433343-d5281380-0d11-11ea-81f7-c441709e0f3b.png)
 
Tela de "NOTÍCIAS"
